- name: install OpenJDK 1.8.0
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: install logstash
  yum:
#    name: /tmp/{{ logstash_package }}
    name: logstash
    state: present

- name: place logstash processing template
  template:
    src: templates/logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf
    force: yes

- name: set service listening address
  lineinfile:
    dest: /etc/logstash/logstash.yml
    regexp: ^http.host
    insertafter: "^# http.host" 
    line: "http.host: {{ ansible_default_ipv4.address | quote }}"

- name: start logstash service
  service:
    name: logstash
    state: started
    enabled: yes

- name: wait for service to begin listening
  wait_for:
    port: 5055
    delay: 30
