---
# ELK playbooks to pre-configure systems, and install/start individual components.
#
# Note: ELK services MUST be brought up in the order below.

- name: install and configure ELK stack
  hosts: all
  gather_facts: true

  vars:
    elk_cluster_name: elk-demo

  roles:
    - role: pre
    - role: elasticsearch
    - role: kibana
    - role: logstash
#    - role: filebeat
#    - role: ssl
#    - role: xpack
